import Foundation

func extractEmbeddingIds(from source: String) -> [String] {
    let pattern = #"NubrickSDK\s*\.\s*embedding(?:UIView)?\s*\(\s*"((?:[^"\\]|\\.)*)""#
    guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
    let ns = source as NSString
    let matches = regex.matches(in: source, range: NSRange(location: 0, length: ns.length))
    return matches.compactMap { match -> String? in
        guard match.numberOfRanges > 1, match.range(at: 1).location != NSNotFound else { return nil }
        let raw = ns.substring(with: match.range(at: 1))
        guard !raw.isEmpty else { return nil }
        return raw.replacingOccurrences(of: #"\""#, with: "\"")
                  .replacingOccurrences(of: #"\\"#, with: "\\")
    }
}

func generateSwiftFile(ids: [String]) -> String {
    let escaped = ids.joined(separator: ",")
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
    return """
    // Generated by NubrickDevTool — DO NOT EDIT.
    import Foundation

    @_cdecl("_nubrick_embedding_ids")
    public func _nubrickEmbeddingIds() -> UnsafeMutablePointer<CChar>? {
        strdup("\(escaped)")
    }

    """
}

// MARK: - Main

guard CommandLine.arguments.count >= 3,
      CommandLine.arguments[1] == "--output" else {
    fputs("Usage: NubrickDevToolRunner --output <path> <swift files...>\n", stderr)
    exit(1)
}

let outputPath = CommandLine.arguments[2]
let inputFiles = Array(CommandLine.arguments.dropFirst(3))

var allIds: [String] = []
var seen = Set<String>()

for filePath in inputFiles {
    guard let data = FileManager.default.contents(atPath: filePath),
          let source = String(data: data, encoding: .utf8) else {
        continue
    }
    for id in extractEmbeddingIds(from: source) {
        if seen.insert(id).inserted {
            allIds.append(id)
        }
    }
}

let generated = generateSwiftFile(ids: allIds)
let outputURL = URL(fileURLWithPath: outputPath)
try! generated.write(to: outputURL, atomically: true, encoding: .utf8)
