use_frameworks!

platform :ios, '10.0'

project 'Nativebrik_Example/Nativebrik_Example.xcodeproj'

target 'Nativebrik_Example' do
  pod 'Nativebrik', :path => '../../'

  target 'Nativebrik_ExampleTests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
