use_frameworks!

platform :ios, '16.4'

project 'Nativebrik_Example/Nativebrik_Example.xcodeproj'

target 'Nativebrik_Example' do
  pod 'Nativebrik', :path => '../../'

  target 'Nativebrik_ExampleTests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end

post_install do |installer|
  puts 'Patching Yoga.cpp to compile with Xcode 14.3'
  %x(patch -N Pods/Yoga/yoga/Yoga.cpp < ./Yoga.cpp.patch || true)
  puts 'Patching frameworks.sh to compile with Xcode 14.3'
  %x(patch -N "Pods/Target Support Files/Pods-Nativebrik_Example/Pods-Nativebrik_Example-frameworks.sh" < ./frameworks.sh.patch || true)
end
