name: Publish Cocoapods
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: macos-26
    environment:
      name: Only Main
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Verify git tag matches podspec version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          PODSPEC_VERSION=$(cat ./Nubrick.podspec | grep -E 's\.version\W+=' | grep -o -e '[0-9]\.[0-9]\.[0-9]')
          test "$TAG_VERSION" = "$PODSPEC_VERSION"

      - name: publish to cocoapods
        run: pod trunk push --verbose Nubrick.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
